import { Bebas_Neue, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Image from "next/image";
import NavigationBar from "@/components/Navbar";
import { SocialMedia } from "@/components/dock";
import { Pointer } from "@/components/magicui/pointer";
import Footer from "@/components/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased dark `}
      >
        <NavigationBar />
        <Providers>
          <div>{children}</div>
        </Providers>
        <SocialMedia />
        <Footer />
      </body>
    </html>
  );
}
